local: &local_storage
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  <<: *local_storage

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
amazon:
  service: S3
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  region: eu-west-2
  bucket: <%= ENV["AWS_BUCKET_NAME"] %>
